/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Arena__factory } from "./Arena__factory";
export { Badges__factory } from "./Badges__factory";
export { GameToken__factory } from "./GameToken__factory";
