version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
