/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Arena } from "./Arena";
export type { Badges } from "./Badges";
export type { GameToken } from "./GameToken";
