[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"  # safe default

[rpc_endpoints]
monad = "${RPC_URL}"

# If Monad gets an Etherscan-style verifier later:
# [etherscan]
# monad = { key = "${ETHER_SCAN_API_KEY}", url = "https://api.explorer-testnet.monad.xyz/api" }
